import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Color from '@/shared/Color'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body style={{backgroundColor:Color.background.silver}}>
        <Header
          language='ja'
        />
        {children}
      </body>
    </html>
  )
}
